const array = [ name= "Matteo",
    surname= "Petrucci",
    age= 25,
    city= "Rieti",
    hobby= "Video Games",
    favoriteFood= "Riso",
    favoriteVideoGame= "League Of Legends",
    favoriteFilm= "Star Wars",
    favoriteBook= "'",
    petName= "Adalgiso, Akita",];
