const array = [
{                         //array Jacopo
    name: "Jacopo",
    surname: "Sangregorio",
    age: 18,
    city: "Paternò",
    hobby: "Music",
    favoriteFood: "Pizza",
    favoriteVideoGame: "Minecraft",
    favoriteFilm: "Interstellar",
    favoriteBook: "The Magic",
    petName: "Lilo",
},
{                           //array Raffaele
    name:"Raffaele",
    surname:"Filannino", 
    age:24, 
    city:"Barletta", 
    hobby:"football", 
    favoriteFood:"Ragu",
    favoriteVideoGame:"Black ops 2", 
    favoriteFilm:"signore degli anelli", 
    favoriteBook:"intelligenza emotiva", 
    petName:"shila",
    },
];
