const array = [
{                         //array Jacopo
    name: "Jacopo",
    surname: "Sangregorio",
    age: 18,
    city: "Paternò",
    hobby: "Music",
    favoriteFood: "Pizza",
    favoriteVideoGame: "Minecraft",
    favoriteFilm: "Interstellar",
    favoriteBook: "The Magic",
    petName: "Lilo",
},
{                           //array Raffaele
    name:"Raffaele",
    surname:"Filannino", 
    age:24, 
    city:"Barletta", 
    hobby:"football", 
    favoriteFood:"Ragu",
    favoriteVideoGame:"Black ops 2", 
    favoriteFilm:"signore degli anelli", 
    favoriteBook:"intelligenza emotiva", 
    petName:"shila",
    },
    {
    name: "Sabrina",
    surname: "Moccia",
    age: 30,
    city: "Rome",
    hobby: "gardening",
    favoriteFood: "carbonara",
    favoriteVideoGame: "Call of Duty",
    favoriteFilm: "The Godfather",
    favoriteBook: "Pride and Prejudice",
    petName: "Nala",
    },
    {
        name: "Tommaso",
        surname: "Merli",
        age: 26,
        city: "Milan",
        hobby: "Video Games",
        favoriteFood: "Carbonara",
        favoriteVideoGame: "League Of Legends",
        favoriteFilm: "Star Wars",
        favoriteBook: "Bible",
        petName: "Leia",
    },    
];
